# Generated by Django 3.0.6 on 2020-08-01 17:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Appraisals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('weightage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('user_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('manager_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('board_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('user_comments', models.CharField(default='NIL', max_length=2000)),
                ('manager_comments', models.CharField(default='NIL', max_length=2000)),
                ('board_comments', models.CharField(default='NIL', max_length=2000)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.User_Appraisal_List')),
            ],
        ),
        migrations.CreateModel(
            name='competency_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departmental_Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Overall_Appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='goal_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('due', models.DateField()),
                ('weightage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('metrics_Used', models.CharField(default='NIL', max_length=100)),
                ('user_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('manager_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('board_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('user_comments', models.CharField(default='NIL', max_length=2000)),
                ('manager_comments', models.CharField(default='NIL', max_length=2000)),
                ('board_comments', models.CharField(default='NIL', max_length=2000)),
                ('tracking_status', models.CharField(choices=[('null', 'null'), ('On Track', 'On Track'), ('Not On Track', 'Not On Track')], default='null', max_length=50, null=True)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.User_Appraisal_List')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile')),
                ('goal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.goal_category')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('due', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('progress', models.CharField(choices=[('Not Started', 'Not Started'), ('Working', 'Working'), ('Completed', 'Completed')], max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.Goals')),
            ],
        ),
        migrations.CreateModel(
            name='goal_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=3000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.Goals')),
            ],
        ),
        migrations.CreateModel(
            name='Departmental_Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('due', models.DateField()),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Overall_Appraisal')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Departments')),
                ('goal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.goal_category')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='departmental_goal_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=3000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('departmental_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.Departmental_Goals')),
            ],
        ),
        migrations.CreateModel(
            name='departmental_competencies_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=3000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('departmental_competencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.Departmental_Competencies')),
            ],
        ),
        migrations.AddField(
            model_name='departmental_competencies',
            name='competency_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.goal_category'),
        ),
        migrations.AddField(
            model_name='departmental_competencies',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Departments'),
        ),
        migrations.AddField(
            model_name='departmental_competencies',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile'),
        ),
        migrations.CreateModel(
            name='competency_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=3000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.Competencies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='competencies',
            name='competency_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.competency_category'),
        ),
        migrations.AddField(
            model_name='competencies',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile'),
        ),
    ]
