# Generated by Django 3.0.6 on 2020-08-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='MID_manager_comments',
            field=models.CharField(default='NIL', max_length=2000),
        ),
        migrations.AddField(
            model_name='goals',
            name='MID_user_comments',
            field=models.CharField(default='NIL', max_length=2000),
        ),
    ]
