# Generated by Django 3.0.6 on 2020-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0002_auto_20200803_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency_category',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
