# Generated by Django 3.0.6 on 2020-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0003_auto_20200806_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency_category',
            name='description',
            field=models.CharField(default='nil', max_length=1000),
            preserve_default=False,
        ),
    ]
