# Generated by Django 3.0.6 on 2020-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0004_competency_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='metrics_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
