# Generated by Django 3.0.6 on 2020-08-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0005_goals_metrics_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='progress',
            field=models.CharField(choices=[('Working', 'Working'), ('Completed', 'Completed')], default='Working', max_length=20),
        ),
    ]
