# Generated by Django 3.0.6 on 2020-08-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0010_auto_20200809_2107'),
        ('GnC', '0006_auto_20200807_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmental_competencies',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.Overall_Appraisal'),
        ),
        migrations.AlterField(
            model_name='departmental_goals',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.Overall_Appraisal'),
        ),
    ]
