# Generated by Django 3.0.6 on 2020-08-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_qualifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
