# Generated by Django 3.0.6 on 2020-08-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_delete_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
