# Generated by Django 3.0.6 on 2020-08-01 17:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overall_Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('goal_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competency_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skill_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('goals_setting_end_date', models.DateField(default=datetime.date.today)),
                ('mid_year_start_date', models.DateField(default=datetime.date.today)),
                ('mid_year_end_date', models.DateField(default=datetime.date.today)),
                ('end_year_start_date', models.DateField(default=datetime.date.today)),
                ('appraisal_end_date', models.DateField(default=datetime.date.today)),
                ('reports_end_date', models.DateField(default=datetime.date.today)),
                ('calibration_end_date', models.DateField(default=datetime.date.today)),
                ('rating_scale', models.CharField(choices=[('Denselight System', 'Denselight System'), ('MiRXes', 'MiRXes')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Stage 1', 'Goals Setting'), ('Stage 1B', 'Mid-Year Review'), ('Stage 2', 'Year-End Review'), ('Stage 3', 'Reports'), ('Stage 4', 'Calibration'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('appraisal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Appraisal_Category')),
            ],
        ),
        migrations.CreateModel(
            name='peerAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('strengthweakness1', models.CharField(blank=True, max_length=1000, null=True)),
                ('development1', models.CharField(blank=True, max_length=5000, null=True)),
                ('title2', models.CharField(default='NIL', max_length=200)),
                ('strengthweakness2', models.CharField(blank=True, max_length=1000, null=True)),
                ('development2', models.CharField(blank=True, max_length=5000, null=True)),
                ('title3', models.CharField(default='NIL', max_length=200)),
                ('strengthweakness3', models.CharField(blank=True, max_length=1000, null=True)),
                ('development3', models.CharField(blank=True, max_length=5000, null=True)),
                ('completion', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('limiter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Appraisal_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('S2Employee', 'S2Employee'), ('S2Manager', 'S2Manager'), ('Approved', 'Approved')], max_length=30)),
                ('appraisal_name', models.CharField(max_length=50, null=True)),
                ('overall_board_comments', models.CharField(blank=True, default='No Comments', max_length=5000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('completion', models.CharField(choices=[('null', 'null'), ('ECompleted', 'ECompleted'), ('MCompleted', 'MCompleted'), ('BCompleted', 'BCompleted'), ('Review', 'Review'), ('ReviewCompleted', 'ReviewCompleted')], default='null', max_length=50, null=True)),
                ('goals_settingM_rejection', models.CharField(default='NIL', max_length=3000)),
                ('appraisalHR_rejection', models.CharField(default='NIL', max_length=3000)),
                ('mid_year_completion', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=15)),
                ('final_employee_rating', models.IntegerField(blank=True, null=True)),
                ('final_manager_rating', models.IntegerField(blank=True, null=True)),
                ('final_board_rating', models.IntegerField(blank=True, null=True)),
                ('appraisal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Appraisal_Category')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Profile.Profile')),
                ('overall_appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Overall_Appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='peerAppraisalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('completed', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.peerAppraisal')),
            ],
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.User_Appraisal_List'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorPA', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersPA', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='Profile.Profile'),
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorA', to='Profile.Profile')),
                ('employee_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.User_Appraisal_List')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersA', to='Profile.Profile')),
                ('rating_scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.Rating_Scale')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userA', to='Profile.Profile')),
            ],
        ),
    ]
