# Generated by Django 3.0.6 on 2020-08-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerappraisal',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='Profile.Profile'),
        ),
    ]
