# Generated by Django 3.0.6 on 2020-08-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0002_auto_20200802_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('S1BEmployee', 'S1BEmployee'), ('S1BManager', 'S1BManager'), ('S1BReview', 'S1BReview'), ('S2Employee', 'S2Employee'), ('S2Manager', 'S2Manager'), ('Approved', 'Approved')], max_length=30),
        ),
    ]
