# Generated by Django 3.0.6 on 2020-08-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0003_auto_20200803_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='mid_yearM_rejection',
            field=models.CharField(default='NIL', max_length=3000),
        ),
    ]
