# Generated by Django 3.0.6 on 2020-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0005_auto_20200805_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='recommendationComments',
            field=models.CharField(default='NIL', max_length=1000),
        ),
    ]
