# Generated by Django 3.0.6 on 2020-08-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0006_user_appraisal_list_recommendationcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='overall_appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.Overall_Appraisal'),
        ),
    ]
