# Generated by Django 3.0.6 on 2020-08-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0007_auto_20200807_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='strengthweakness1',
            new_name='strength1',
        ),
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='strengthweakness2',
            new_name='strength2',
        ),
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='strengthweakness3',
            new_name='strength3',
        ),
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='development1',
            new_name='weaknessdevelopment1',
        ),
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='development2',
            new_name='weaknessdevelopment2',
        ),
        migrations.RenameField(
            model_name='peerappraisal',
            old_name='development3',
            new_name='weaknessdevelopment3',
        ),
    ]
