# Generated by Django 3.0.6 on 2020-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0009_auto_20200809_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_appraisal',
            name='rating_scale',
            field=models.CharField(choices=[('Denselight System', 'Denselight System'), ('MiRXes', 'MiRXes')], default='Denselight System', max_length=50, null=True),
        ),
    ]
